spring:
  application:
#    应用名称
    name: reggie
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url后边加参数,防乱码
    url: jdbc:mysql://ip.izyq.cn:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: n1mysql666
  servlet:
    multipart:
      file-size-threshold: 102400

#      redis配置
  redis:
    host: ip.izyq.cn
    port: 6379
    database: 0
    password: n1redis666
  cache:
    redis:
      time-to-live: 1800000
server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #主键类型
      id-type: assign_id

reggie:
  path: 图片资源/